#!/bin/sh
HOST=$1
BASEDIR=$2
NUM=$3

DIR=`dirname $0`
LIBPATH="${DIR}/lib"
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="ITAndroids"
teamlogo="${DIR}/team_logo.xpm"
player="${DIR}/ITAndroids_player"
coach="${DIR}/ITAndroids_coach"
player_config="${DIR}/player.conf"
coach_config="${DIR}/coach.conf"
config_dir="${DIR}/formations-dt"
host=$HOST
port=6000
coach_port=""
team_graphic="--use_team_graphic on --team_graphic_file ${teamlogo}"
matching_type="1"

if [ X"${coach_port}" = X'' ]; then
  coach_port=`expr ${port} + 2`
fi
ping -c 1 $host
common_opt=""
common_opt="${common_opt} -h ${host} -t ${teamname}"
player_opt="--player-config ${player_config}"
player_opt="${player_opt} --config_dir ${config_dir}"
player_opt="${player_opt} --matching-type ${matching_type}"
player_opt="${player_opt} ${common_opt}"
player_opt="${player_opt} -p ${port}"
coach_opt="--coach-config ${coach_config}"
coach_opt="${coach_opt} ${common_opt}"
coach_opt="${coach_opt} -p ${coach_port}"
coach_opt="${coach_opt} ${team_graphic}"

cd $BASEDIR
case $NUM in
    1)
        $player ${player_opt} -g
        ;;
    12)
        $coach ${coach_opt}
        ;;
    *)
        $player ${player_opt}
        ;;
esac
