Formation Static
# ---------------------------------------------------------
1 Goalie		-16.50	-7.80
2 CenterBack		-16.50	3.15
3 CenterBack		-16.50	-2.32
4 SideBack		-16.50	8.63
5 SideBack		-21.46	8.63
6 DefensiveHalf		-26.42	8.63
7 OffensiveHalf		-28.42	5.00
8 OffensiveHalf		-26.42	2.80
9  SideForward		-26.42	-7.80
10 SideForward		-24.00	-4.00
11 CenterForward	-21.46	0.00
# ---------------------------------------------------------
