#!/bin/sh
HOST=$1
BASEDIR=$2
NUM=$3

LIBPATH=./lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

DIR=`dirname $0`

teamname="red_dragons"

player="${DIR}/red_dragons_player"
coach="${DIR}/red_dragons_coach"

config="${DIR}/player.conf"
config_dir="${DIR}/formations-dt"
coach_config="${DIR}/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

team_graphic="--use_team_graphic on --team_graphic_file ${DIR}/team_logo.xpm"
coachopt="${coachopt} ${team_graphic}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
