#!/bin/sh

# change the following informations according to your needs.

HOST=$1
BASEDIR=$2
NUM=$3

DIR=`dirname $0`

LIBPATH="${DIR}/lib"
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

# Put here the name of your team
teamname="TitasDaRobotica"
player="${DIR}/titans_player"
coach="${DIR}/titans_coach"
config="${DIR}/player.conf"
config_dir="${DIR}/formations"
coach_config="${DIR}/coach.conf"

team_graphic="--use_team_graphic on"
opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"
coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"
coachopt="${coachopt} ${team_graphic}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
